import React, {useCallback, useEffect, useMemo, useRef, useState} from 'react';

const API='/api';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const date=v=>new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(new Date(v));
const uid=()=>Math.random().toString(36).slice(2,9);

function Icon({name,size=20,strokeWidth=1.8}){
  const paths={
    grid:<><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>,
    pattern:<><path d="M4 3h11l5 5v13H4z"/><path d="M15 3v5h5M8 13h8M8 17h6"/></>,
    store:<><path d="M3 9l2-5h14l2 5M5 13v8h14v-8"/><path d="M3 9a3 3 0 006 0 3 3 0 006 0 3 3 0 006 0M9 21v-6h6v6"/></>,
    bag:<><path d="M5 8h14l-1 13H6z"/><path d="M9 9V6a3 3 0 016 0v3"/></>,
    chart:<><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></>,
    heart:<path d="M20.8 4.6a5.5 5.5 0 00-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 00-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 00-.1-7.8z"/>,
    folder:<path d="M3 5h6l2 2h10v12a2 2 0 01-2 2H5a2 2 0 01-2-2z"/>,
    user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0116 0"/></>,
    plus:<><path d="M12 5v14M5 12h14"/></>,
    search:<><circle cx="11" cy="11" r="7"/><path d="M20 20l-4-4"/></>,
    chevron:<path d="M9 18l6-6-6-6"/>,
    down:<path d="M6 9l6 6 6-6"/>,
    arrow:<><path d="M5 12h14M13 6l6 6-6 6"/></>,
    back:<><path d="M19 12H5M11 18l-6-6 6-6"/></>,
    more:<><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>,
    edit:<><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 013 3L8 18l-4 1 1-4z"/></>,
    eye:<><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/></>,
    download:<><path d="M12 3v12M7 10l5 5 5-5M4 21h16"/></>,
    upload:<><path d="M12 16V4M7 9l5-5 5 5M4 20h16"/></>,
    check:<path d="M5 12l4 4L19 6"/>,
    clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
    settings:<><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 00.3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 00-1.9-.3 1.7 1.7 0 00-1 1.6V21H9v-.1a1.7 1.7 0 00-1-1.6 1.7 1.7 0 00-1.9.3l-.1.1L3.2 17l.1-.1a1.7 1.7 0 00.3-1.9A1.7 1.7 0 002 14H2v-4h.1a1.7 1.7 0 001.6-1 1.7 1.7 0 00-.3-1.9L3.2 7 6 4.2l.1.1a1.7 1.7 0 001.9.3A1.7 1.7 0 009 3V3h4v.1a1.7 1.7 0 001 1.6 1.7 1.7 0 001.9-.3l.1-.1L17.8 7l-.1.1a1.7 1.7 0 00-.3 1.9 1.7 1.7 0 001.6 1H21v4h-.1a1.7 1.7 0 00-1.5 1z"/></>,
    logout:<><path d="M10 4H4v16h6M14 8l4 4-4 4M8 12h10"/></>,
    scissors:<><circle cx="6" cy="7" r="3"/><circle cx="6" cy="17" r="3"/><path d="M8.5 8.5L21 3M8.5 15.5L21 21M12 12l9-4"/></>,
    yarn:<><circle cx="12" cy="12" r="9"/><path d="M5 8c5-2 10 1 14 5M4 13c5-2 10 1 13 5M9 4c0 5 3 10 8 14"/></>,
    star:<path d="M12 2.5l3 6 6.5 1-4.7 4.6 1.1 6.4-5.9-3.1-5.9 3.1 1.1-6.4-4.7-4.6 6.5-1z"/>,
    spark:<path d="M12 2l1.7 6.3L20 10l-6.3 1.7L12 18l-1.7-6.3L4 10l6.3-1.7z"/>,
    trash:<><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14M10 11v6M14 11v6"/></>,
    image:<><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8" cy="9" r="2"/><path d="M3 17l5-5 4 4 3-3 6 6"/></>,
    menu:<><path d="M4 6h16M4 12h16M4 18h16"/></>,
    close:<><path d="M6 6l12 12M18 6L6 18"/></>,
    lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 018 0v3"/></>,
  };
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.pattern}</svg>;
}

async function request(path,options={}){
  const token=localStorage.getItem('stitch_token');
  const headers={...(options.body&&!(options.body instanceof FormData)?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{}) ,...options.headers};
  const res=await fetch(`${API}${path}`,{...options,headers,body:options.body&&!(options.body instanceof FormData)&&typeof options.body!=='string'?JSON.stringify(options.body):options.body});
  if(!res.ok){let body={};try{body=await res.json();}catch{}throw new Error(body.error||`Request failed (${res.status})`);}
  if(res.status===204)return null;
  return res.json();
}

async function downloadFile(path,fallback='pattern.pdf'){
  const token=localStorage.getItem('stitch_token');
  const res=await fetch(`${API}${path}`,{headers:{Authorization:`Bearer ${token}`}});
  if(!res.ok){let b={};try{b=await res.json();}catch{}throw new Error(b.error||'Download failed.');}
  const blob=await res.blob();
  const cd=res.headers.get('content-disposition');
  const file=cd?.match(/filename="([^"]+)"/)?.[1]||fallback;
  const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);
}

function Logo({compact=false}){return <div className={`logo ${compact?'compact':''}`}><div className="logo-mark"><Icon name="scissors" size={20}/></div>{!compact&&<div><b>Stitch</b> Market</div>}</div>}
function Avatar({user,size='md'}){const initials=(user?.name||'SM').split(' ').map(x=>x[0]).slice(0,2).join('');return <span className={`avatar ${size}`} style={{background:user?.avatarColor||'#d77559'}}>{initials}</span>}
function Stars({value=0,count=true}){return <span className="stars"><span>{[1,2,3,4,5].map(n=><Icon key={n} name="star" size={13} strokeWidth={n<=Math.round(value)?0:1.7}/>)}</span>{count&&<b>{value?Number(value).toFixed(1):'New'}</b>}</span>}
function Status({value}){return <span className={`status ${value}`}><i/>{value}</span>}
function Empty({icon='pattern',title,text,action}){return <div className="empty"><span><Icon name={icon} size={28}/></span><h3>{title}</h3><p>{text}</p>{action}</div>}
function Loading(){return <div className="loading"><div className="spinner"/><span>Setting up your workspace…</span></div>}
function Field({label,hint,children,className=''}){return <label className={`field ${className}`}><span className="field-label">{label}{hint&&<small>{hint}</small>}</span>{children}</label>}
function Btn({children,variant='primary',icon,onClick,type='button',disabled=false,className=''}){return <button type={type} className={`btn ${variant} ${className}`} onClick={onClick} disabled={disabled}>{icon&&<Icon name={icon} size={17}/>}<span>{children}</span></button>}
function PageTitle({eyebrow,title,sub,actions}){return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{sub&&<p>{sub}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</div>}

function CoverArt({pattern,large=false}){
  if(pattern.coverImage)return <div className={`cover-art image ${large?'large':''}`}><img src={pattern.coverImage} alt=""/><div className="cover-badge">{pattern.type}</div></div>;
  const sewing=pattern.type==='sewing';
  return <div className={`cover-art ${sewing?'sewing':'crochet'} ${large?'large':''}`}>
    <div className="cover-grid"/><span className="cover-brand">STITCH MARKET</span>
    <div className="cover-illustration">{sewing?<svg viewBox="0 0 180 180"><path d="M73 25l17 12 17-12 29 20-18 28-9-9 8 87H62l8-87-9 9-18-28z"/><path d="M72 60c13 9 24 9 36 0M90 37v114"/></svg>:<svg viewBox="0 0 180 180"><circle cx="90" cy="90" r="56"/><circle cx="90" cy="90" r="43"/><path d="M48 85c20-35 64-29 84 4M53 110c24-28 54-27 75-5M67 48c-8 23 4 69 47 84"/></svg>}</div>
    <div className="cover-copy"><small>{pattern.category||'Original pattern'}</small><b>{pattern.title}</b><span>{pattern.difficulty} · {(pattern.sizes||[]).join(' / ')}</span></div>
  </div>;
}

function Auth({onAuth}){
  const [mode,setMode]=useState('login');const [form,setForm]=useState({name:'',studio:'',email:'',password:''});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const submit=async(e,override)=>{e?.preventDefault();setBusy(true);setError('');try{const data=await request(`/auth/${mode}`,{method:'POST',body:override||form});localStorage.setItem('stitch_token',data.token);onAuth(data.user);}catch(err){setError(err.message);}finally{setBusy(false)}};
  return <main className="auth-page">
    <section className="auth-story"><Logo/><div className="story-copy"><span className="pill light"><Icon name="spark" size={14}/> Your pattern studio, beautifully organized</span><h1>From first stitch<br/>to <em>finished pattern.</em></h1><p>Create professional sewing and crochet patterns, publish polished PDFs, and grow your creative business—all in one calm workspace.</p><div className="story-features"><span><Icon name="pattern"/>Visual pattern builder</span><span><Icon name="download"/>Print-ready PDF export</span><span><Icon name="store"/>Built-in marketplace</span></div></div><div className="auth-preview"><div className="mini-card one"><Icon name="scissors"/><b>Sewing pattern</b><small>A4 tiles ready</small></div><div className="mini-card two"><Icon name="yarn"/><b>Crochet chart</b><small>Gauge checked</small></div></div><small className="auth-foot">Made for independent makers everywhere.</small></section>
    <section className="auth-form-wrap"><div className="auth-form"><div className="auth-mobile-logo"><Logo/></div><span className="eyebrow">WELCOME TO STITCH MARKET</span><h2>{mode==='login'?'Sign in to your studio':'Create your studio'}</h2><p>{mode==='login'?'Keep creating where you left off.':'Your first professional pattern starts here.'}</p>
      <form onSubmit={submit}>{mode==='register'&&<div className="form-grid two"><Field label="Your name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Maya Chen"/></Field><Field label="Studio name"><input value={form.studio} onChange={e=>setForm({...form,studio:e.target.value})} placeholder="Thread & Form"/></Field></div>}
      <Field label="Email address"><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@studio.com"/></Field><Field label="Password"><input type="password" required minLength={6} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 6 characters"/></Field>
      {error&&<div className="form-error">{error}</div>}<Btn type="submit" disabled={busy} className="full">{busy?'Please wait…':mode==='login'?'Sign in':'Create free account'}</Btn></form>
      {mode==='login'&&<><div className="or"><span/>or try the ready-made studio<span/></div><button className="demo-login" onClick={()=>submit(null,{email:'maya@stitch.market',password:'demo123'})}><span><Avatar user={{name:'Maya Chen',avatarColor:'#d77559'}}/><span><b>Open demo workspace</b><small>maya@stitch.market · demo123</small></span></span><Icon name="arrow"/></button></>}
      <p className="auth-switch">{mode==='login'?"New to Stitch Market? ":'Already have an account? '}<button onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Create an account':'Sign in'}</button></p>
    </div></section>
  </main>
}

const nav=[['dashboard','grid','Overview'],['patterns','pattern','My patterns'],['marketplace','store','Marketplace'],['orders','bag','Purchases'],['sales','chart','Sales'],['favorites','heart','Favorites'],['collections','folder','Collections']];
function Shell({user,page,navigate,onNew,onLogout,children}){
  const [mobile,setMobile]=useState(false);
  const go=p=>{navigate(p);setMobile(false)};
  return <div className="app-shell"><aside className={`sidebar ${mobile?'open':''}`}><div className="side-top"><Logo/><button className="mobile-close" onClick={()=>setMobile(false)}><Icon name="close"/></button></div><Btn icon="plus" onClick={()=>{onNew();setMobile(false)}} className="new-pattern">New pattern</Btn><nav>{nav.map(([key,icon,label])=><button key={key} className={page===key?'active':''} onClick={()=>go(key)}><Icon name={icon}/><span>{label}</span>{key==='marketplace'&&<i className="new-dot">NEW</i>}</button>)}</nav><div className="side-bottom"><button className={page==='profile'?'active':''} onClick={()=>go('profile')}><Avatar user={user}/><span><b>{user.name}</b><small>{user.studio||'Creator studio'}</small></span><Icon name="more"/></button><button className="logout" onClick={onLogout}><Icon name="logout"/><span>Sign out</span></button></div></aside>{mobile&&<div className="backdrop" onClick={()=>setMobile(false)}/>}<div className="main-wrap"><header className="mobile-header"><button onClick={()=>setMobile(true)}><Icon name="menu"/></button><Logo/><button onClick={onNew}><Icon name="plus"/></button></header><main className="content">{children}</main></div></div>
}

function Dashboard({user,navigate,onNew,onEdit,toast}){
  const [data,setData]=useState(null);useEffect(()=>{request('/dashboard').then(setData).catch(e=>toast(e.message,'error'))},[]);
  if(!data)return <Loading/>;
  const s=data.stats;
  return <><PageTitle eyebrow="CREATOR STUDIO" title={`Good morning, ${user.name.split(' ')[0]}.`} sub="Here's what's happening with your pattern business." actions={<Btn icon="plus" onClick={onNew}>Create pattern</Btn>}/>
    <section className="stats-grid"><div className="stat-card coral"><span><Icon name="pattern"/></span><div><b>{s.patterns}</b><small>Total patterns</small></div><i>+2 this month</i></div><div className="stat-card sage"><span><Icon name="store"/></span><div><b>{s.published}</b><small>Published</small></div><i>{s.drafts} in draft</i></div><div className="stat-card sand"><span><Icon name="bag"/></span><div><b>{s.sales}</b><small>Pattern sales</small></div><i>Verified orders</i></div><div className="stat-card dark"><span><Icon name="chart"/></span><div><b>{money(s.revenue)}</b><small>Total revenue</small></div><i>Test mode</i></div></section>
    <section className="dashboard-grid"><div className="panel recent-panel"><div className="panel-head"><div><h2>Continue creating</h2><p>Your recently edited patterns</p></div><button onClick={()=>navigate('patterns')}>View all <Icon name="arrow" size={15}/></button></div><div className="recent-list">{data.recent.map(p=><button key={p.id} className="recent-row" onClick={()=>onEdit(p.id)}><CoverArt pattern={p}/><div><b>{p.title}</b><small><span className={`craft ${p.type}`}>{p.type==='sewing'?<Icon name="scissors" size={12}/>:<Icon name="yarn" size={12}/>} {p.type}</span> · Edited {date(p.updatedAt)}</small></div><Status value={p.status}/><Icon name="chevron"/></button>)}</div></div>
      <div className="panel quick-panel"><div className="panel-head"><div><h2>Quick start</h2><p>What will you make today?</p></div></div><button className="quick sewing" onClick={()=>onNew('sewing')}><span><Icon name="scissors" size={25}/></span><div><b>Sewing pattern</b><small>Garments, bags & accessories</small></div><Icon name="arrow"/></button><button className="quick crochet" onClick={()=>onNew('crochet')}><span><Icon name="yarn" size={25}/></span><div><b>Crochet pattern</b><small>Wearables, toys & home</small></div><Icon name="arrow"/></button><div className="tip"><Icon name="spark"/><div><b>Creator tip</b><p>Patterns with a cover and complete size chart see more marketplace saves.</p></div></div></div>
    </section>
    <section className="studio-banner"><div><span className="eyebrow">STITCH MARKET STUDIO</span><h2>Turn your process into a polished product.</h2><p>Add instructions, diagrams and printable pieces—we'll handle the professional PDF layout.</p><Btn variant="cream" icon="spark" onClick={onNew}>Start a fresh pattern</Btn></div><div className="banner-art"><span className="paper p1">A4</span><span className="paper p2"><Icon name="scissors"/></span><span className="paper p3"><Icon name="yarn"/></span></div></section>
  </>
}

function PatternCard({p,onEdit,onFavorite,market=false,onOpen}){
  return <article className="pattern-card"><button className="cover-button" onClick={()=>market?onOpen(p.id):onEdit(p.id)}><CoverArt pattern={p}/>{p.featured&&<span className="featured"><Icon name="spark" size={12}/> Featured</span>}</button><div className="pattern-card-body"><div className="card-meta"><span className={`craft ${p.type}`}>{p.type==='sewing'?<Icon name="scissors" size={12}/>:<Icon name="yarn" size={12}/>} {p.type}</span>{market?<button className={`heart ${p.isFavorite?'on':''}`} onClick={()=>onFavorite(p)}><Icon name="heart" size={18}/></button>:<Status value={p.status}/>}</div><button className="card-title" onClick={()=>market?onOpen(p.id):onEdit(p.id)}>{p.title}</button><p>{p.description||'Add a description to introduce your pattern.'}</p>{market?<><div className="seller"><Avatar user={p.creator} size="xs"/><span>{p.creator?.studio||p.creator?.name}</span></div><div className="price-row"><Stars value={p.rating}/><b>{money(p.price)}</b></div></>:<><div className="pattern-specs"><span>{p.difficulty}</span><span>{(p.sizes||[]).length} size{(p.sizes||[]).length!==1?'s':''}</span><span>{money(p.price)}</span></div><div className="card-actions"><button onClick={()=>onEdit(p.id)}><Icon name="edit" size={15}/> Edit pattern</button><button><Icon name="more"/></button></div></>}</div></article>
}

function Library({mode='patterns',onEdit,onNew,onOpenProduct,toast}){
  const [items,setItems]=useState(null),[query,setQuery]=useState(''),[status,setStatus]=useState(mode==='favorites'?'all':'all'),[type,setType]=useState('all'),[collection,setCollection]=useState(''),[collections,setCollections]=useState([]);
  const load=useCallback(()=>{const q=new URLSearchParams();if(query)q.set('search',query);if(status!=='all')q.set('status',status);if(type!=='all')q.set('type',type);if(mode==='favorites')q.set('favorite','true');if(collection)q.set('collection',collection);request(`/patterns?${q}`).then(setItems).catch(e=>toast(e.message,'error'))},[query,status,type,mode,collection,toast]);
  useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[load]);useEffect(()=>{request('/collections').then(setCollections)},[]);
  const isCollections=mode==='collections';
  return <><PageTitle eyebrow="PATTERN LIBRARY" title={mode==='favorites'?'Your favorites':isCollections?'Collections':'My patterns'} sub={mode==='favorites'?'Patterns you want to keep close.':isCollections?'Group patterns into calm, useful spaces.':'Create, organize and publish your original designs.'} actions={<Btn icon="plus" onClick={onNew}>New pattern</Btn>}/>
    {isCollections&&<div className="collection-strip"><button className={!collection?'selected':''} onClick={()=>setCollection('')}><span><Icon name="folder"/></span><b>All patterns</b><small>{items?.length||0} items</small></button>{collections.map(c=><button className={collection===c.name?'selected':''} key={c.name} onClick={()=>setCollection(c.name)}><span><Icon name="folder"/></span><b>{c.name}</b><small>{c.count} items</small></button>)}<button className="new-collection" onClick={()=>toast('Add a collection name inside any pattern’s Publish tab.')}><span><Icon name="plus"/></span><b>New collection</b><small>Organize your work</small></button></div>}
    <div className="toolbar"><div className="search"><Icon name="search"/><input placeholder="Search your patterns…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-tabs">{!isCollections&&mode!=='favorites'&&['all','draft','published'].map(x=><button key={x} className={status===x?'active':''} onClick={()=>setStatus(x)}>{x}</button>)}</div><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All crafts</option><option value="sewing">Sewing</option><option value="crochet">Crochet</option></select></div>
    {!items?<Loading/>:items.length?<div className="patterns-grid">{items.map(p=>mode==='favorites'?<PatternCard p={{...p,isFavorite:true}} key={p.id} market onOpen={onOpenProduct} onFavorite={async()=>{try{await request(`/patterns/${p.id}/favorite`,{method:'POST'});load()}catch(e){toast(e.message,'error')}}}/>:<PatternCard p={p} key={p.id} onEdit={onEdit}/>)}</div>:<Empty icon={mode==='favorites'?'heart':'pattern'} title={query?'No matching patterns':mode==='favorites'?'No favorites yet':'Your pattern shelf is ready'} text={query?'Try a different title, category or filter.':'Create your first pattern and watch your library take shape.'} action={<Btn icon="plus" onClick={onNew}>Create a pattern</Btn>}/>}</>
}

function Marketplace({onOpen,toast}){
  const [items,setItems]=useState(null),[search,setSearch]=useState(''),[type,setType]=useState('all'),[difficulty,setDifficulty]=useState('all'),[sort,setSort]=useState('featured');
  const load=useCallback(()=>{const q=new URLSearchParams({type,difficulty,sort});if(search)q.set('search',search);request(`/marketplace?${q}`).then(setItems).catch(e=>toast(e.message,'error'))},[search,type,difficulty,sort,toast]);
  useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[load]);
  const favorite=async p=>{try{await request(`/patterns/${p.id}/favorite`,{method:'POST'});load()}catch(e){toast(e.message,'error')}};
  return <><section className="market-hero"><div><span className="eyebrow">THE MAKER MARKETPLACE</span><h1>Patterns made with<br/><em>care, for makers.</em></h1><p>Discover thoughtfully designed sewing and crochet patterns from independent creators.</p><div className="hero-search"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search dresses, cardigans, blankets…"/><Btn>Search</Btn></div></div><div className="market-orbit"><div className="orbit-center"><Icon name="spark" size={30}/><b>Made by<br/>independents</b></div><span className="orbit one"><Icon name="scissors"/></span><span className="orbit two"><Icon name="yarn"/></span><span className="orbit three"><Icon name="heart"/></span></div></section>
    <div className="market-head"><div><h2>Explore patterns</h2><p>{items?.length||0} original digital patterns</p></div><div className="market-filters"><div className="segmented">{[['all','All'],['sewing','Sewing'],['crochet','Crochet']].map(([k,l])=><button className={type===k?'active':''} onClick={()=>setType(k)} key={k}>{l}</button>)}</div><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="all">Any difficulty</option><option>Beginner</option><option>Confident beginner</option><option>Intermediate</option><option>Advanced</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="popular">Most popular</option><option value="newest">Newest</option><option value="price-low">Price: low to high</option></select></div></div>
    {!items?<Loading/>:items.length?<div className="patterns-grid market-grid">{items.map(p=><PatternCard key={p.id} p={p} market onOpen={onOpen} onFavorite={favorite}/>)}</div>:<Empty icon="search" title="No patterns found" text="Try another keyword or broaden your filters."/>}</>
}

function Product({id,onBack,onEdit,toast,user}){
  const [p,setP]=useState(null),[busy,setBusy]=useState(false),[format,setFormat]=useState('a4');
  const load=()=>request(`/marketplace/${id}`).then(setP).catch(e=>toast(e.message,'error'));useEffect(load,[id]);
  const buy=async()=>{setBusy(true);try{await request('/orders',{method:'POST',body:{patternId:p.id}});toast('Purchase complete — your PDF is ready.','success');load()}catch(e){toast(e.message,'error')}finally{setBusy(false)}};
  const favorite=async()=>{try{await request(`/patterns/${p.id}/favorite`,{method:'POST'});load()}catch(e){toast(e.message,'error')}};
  if(!p)return <Loading/>;const owner=p.userId===user.id;
  return <><button className="back-link" onClick={onBack}><Icon name="back"/> Back to marketplace</button><div className="product-layout"><div className="product-cover"><CoverArt pattern={p} large/><div className="pdf-note"><Icon name="pattern"/><span><b>Professional PDF included</b><small>{p.type==='sewing'?'A4 and US Letter printable files':'Formatted digital pattern with chart'}</small></span></div></div><div className="product-info"><div className="product-badges"><span className={`craft ${p.type}`}>{p.type==='sewing'?<Icon name="scissors"/>:<Icon name="yarn"/>}{p.type}</span><span>{p.category}</span></div><h1>{p.title}</h1><div className="byline"><Avatar user={p.creator}/><span>Designed by <b>{p.creator?.studio||p.creator?.name}</b></span><Stars value={p.rating}/></div><p className="product-desc">{p.description}</p><div className="product-spec-grid"><div><small>DIFFICULTY</small><b>{p.difficulty}</b></div><div><small>SIZES</small><b>{(p.sizes||[]).join(', ')}</b></div>{p.type==='crochet'?<><div><small>YARN</small><b>{p.yarnWeight||'Any'}</b></div><div><small>HOOK</small><b>{p.hookSize||'See pattern'}</b></div></>:<><div><small>PIECES</small><b>{p.pieces?.length||0} printable</b></div><div><small>FORMAT</small><b>A4 + Letter</b></div></>}</div><div className="purchase-box"><div><small>DIGITAL DOWNLOAD</small><b>{money(p.price)}</b></div>{owner?<Btn icon="edit" onClick={()=>onEdit(p.id)}>Edit your pattern</Btn>:p.purchased?<div className="purchased-actions"><select value={format} onChange={e=>setFormat(e.target.value)}><option value="a4">A4 PDF</option><option value="letter">US Letter PDF</option></select><Btn icon="download" onClick={()=>downloadFile(`/patterns/${p.id}/export?format=${format}`).catch(e=>toast(e.message,'error'))}>Download</Btn></div>:<Btn icon="lock" disabled={busy} onClick={buy}>{busy?'Processing…':`Buy pattern · ${money(p.price)}`}</Btn>}<button className={`save-product ${p.isFavorite?'on':''}`} onClick={favorite}><Icon name="heart"/>{p.isFavorite?'Saved to favorites':'Save for later'}</button><p><Icon name="lock" size={13}/> Test checkout · instant secure download</p></div></div></div>
    <section className="product-details"><div><span className="eyebrow">INSIDE THE PATTERN</span><h2>Everything you need to make it beautifully.</h2></div><div className="includes-grid"><div><Icon name="pattern"/><b>Clear instructions</b><p>{p.instructions?.length||0} carefully written construction steps.</p></div><div><Icon name={p.type==='sewing'?'scissors':'yarn'}/><b>{p.type==='sewing'?'Printable pieces':'Stitch guidance'}</b><p>{p.type==='sewing'?`${p.pieces?.length||0} drafted pieces with seam allowances.`:`Gauge, abbreviations and ${p.rows?.length||0} row sequences.`}</p></div><div><Icon name="download"/><b>Polished PDF</b><p>Cover, materials, page numbers and copyright included.</p></div></div></section>
    <section className="reviews"><div className="panel-head"><div><h2>Maker reviews</h2><p>Feedback from verified buyers</p></div><Stars value={p.rating}/></div>{p.reviews?.length?p.reviews.map(r=><div className="review" key={r.id}><Avatar user={r.user}/><div><b>{r.user.name}</b><Stars value={r.rating} count={false}/><p>{r.comment}</p><small>{date(r.createdAt)} · Verified purchase</small></div></div>):<Empty icon="star" title="Be the first to review" text="Verified buyers can share their experience."/>}</section></>
}

function Repeater({items,onChange,empty,render,newItem,addLabel}){
  return <div className="repeater">{items?.length?items.map((item,i)=><div key={item._key||i} className="repeat-row">{render(item,i,(patch)=>onChange(items.map((x,n)=>n===i?{...x,...patch}:x)))}<button className="remove" onClick={()=>onChange(items.filter((_,n)=>n!==i))}><Icon name="trash" size={16}/></button></div>):empty&&<p className="repeat-empty">{empty}</p>}<button className="add-row" onClick={()=>onChange([...(items||[]),{...newItem,_key:uid()}])}><Icon name="plus" size={15}/>{addLabel}</button></div>
}
function ChipInput({values=[],onChange,placeholder='Type and press Enter'}){const [v,setV]=useState('');const add=()=>{if(v.trim()&&!values.includes(v.trim()))onChange([...values,v.trim()]);setV('')};return <div className="chip-input"><div>{values.map(x=><span key={x}>{x}<button onClick={()=>onChange(values.filter(y=>y!==x))}>×</button></span>)}</div><input value={v} placeholder={placeholder} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'||e.key===','){e.preventDefault();add()}}} onBlur={add}/></div>}

function PatternPreview({p,onClose}){return <div className="preview-drawer"><div className="preview-head"><div><span className="eyebrow">LIVE PREVIEW</span><h3>Pattern PDF</h3></div><button onClick={onClose}><Icon name="close"/></button></div><div className="preview-scroll"><div className="preview-page cover"><CoverArt pattern={p}/><span className="eyebrow">{p.type} pattern</span><h1>{p.title}</h1><p>{p.description}</p><small>{(p.sizes||[]).join(' · ')}</small></div><div className="preview-page"><span className="page-no">02</span><span className="eyebrow">PATTERN OVERVIEW</span><h2>Materials & tools</h2><div className="preview-rule"/><h4>Materials</h4><ul>{p.materials?.map((m,i)=><li key={i}>{m.name} <small>{m.quantity}</small></li>)}</ul><h4>Tools</h4><ul>{p.tools?.map(x=><li key={x}>{x}</li>)}</ul></div><div className="preview-page"><span className="page-no">03</span><span className="eyebrow">MAKE IT</span><h2>Instructions</h2><div className="preview-rule"/>{p.instructions?.map((s,i)=><div className="preview-step" key={i}><b>{i+1}</b><div><h4>{s.title}</h4><p>{s.body}</p></div></div>)}</div></div></div>}

const categoryMap={sewing:['Apparel','Dresses','Tops','Bottoms','Bags','Accessories','Kids'],crochet:['Garments','Accessories','Home','Amigurumi','Baby','Blankets']};
function Editor({id,onBack,toast}){
  const [p,setP]=useState(null),[tab,setTab]=useState('details'),[saveState,setSaveState]=useState('saved'),[preview,setPreview]=useState(false),dirty=useRef(false),saving=useRef(false);
  useEffect(()=>{request(`/patterns/${id}`).then(setP).catch(e=>toast(e.message,'error'))},[id]);
  const update=patch=>{dirty.current=true;setSaveState('unsaved');setP(x=>({...x,...patch}))};
  const save=useCallback(async(showToast=false)=>{if(!p||saving.current)return;saving.current=true;setSaveState('saving');try{const out=await request(`/patterns/${p.id}`,{method:'PUT',body:p});dirty.current=false;setP(out);setSaveState('saved');if(showToast)toast('Pattern saved.','success');}catch(e){setSaveState('error');toast(e.message,'error')}finally{saving.current=false}},[p,toast]);
  useEffect(()=>{if(!p||!dirty.current)return;const t=setTimeout(()=>save(),1100);return()=>clearTimeout(t)},[p,save]);
  const exportPdf=format=>{save().then(()=>downloadFile(`/patterns/${p.id}/export?format=${format}`)).catch(e=>toast(e.message,'error'))};
  const publish=async()=>{if(!p.title.trim())return toast('Add a title before publishing.','error');if(!p.instructions?.some(x=>x.body.trim()))return toast('Add at least one complete instruction.','error');const next={...p,status:'published'};saving.current=true;setSaveState('saving');setP(next);try{const out=await request(`/patterns/${p.id}`,{method:'PUT',body:next});dirty.current=false;setP(out);setSaveState('saved');toast(p.status==='published'?'Marketplace listing updated.':'Pattern published to the marketplace.','success')}catch(e){setSaveState('error');toast(e.message,'error')}finally{saving.current=false}};
  const image=e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>3_000_000)return toast('Please choose an image smaller than 3 MB.','error');const r=new FileReader();r.onload=()=>update({coverImage:r.result});r.readAsDataURL(file)};
  if(!p)return <Loading/>;
  const set=(k,v)=>update({[k]:v});
  return <div className="editor-shell"><div className="editor-top"><button className="back-link" onClick={onBack}><Icon name="back"/> My patterns</button><div className="editor-title"><span className={`craft ${p.type}`}>{p.type==='sewing'?<Icon name="scissors"/>:<Icon name="yarn"/>}{p.type}</span><input value={p.title} onChange={e=>set('title',e.target.value)}/></div><div className={`save-state ${saveState}`}><Icon name={saveState==='saved'?'check':'clock'} size={15}/>{saveState==='saving'?'Saving…':saveState==='unsaved'?'Unsaved changes':saveState==='error'?'Save failed':'All changes saved'}</div><Btn variant="secondary" icon="eye" onClick={()=>setPreview(true)}>Preview</Btn><Btn icon="download" onClick={()=>exportPdf(p.paperSize==='Letter'?'letter':'a4')}>Export PDF</Btn></div>
    <div className="editor-tabs">{[['details','1','Pattern details'],['craft','2',p.type==='sewing'?'Sewing tools':'Crochet tools'],['instructions','3','Instructions'],['publish','4','Preview & publish']].map(([k,n,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><i>{n}</i>{l}<Icon name="chevron" size={14}/></button>)}</div>
    <div className="editor-content">
    {tab==='details'&&<section className="editor-section"><div className="section-intro"><span className="eyebrow">THE ESSENTIALS</span><h2>Tell makers about your pattern.</h2><p>Clear details build buyer confidence and make your PDF feel considered.</p></div><div className="editor-grid"><div className="form-card"><h3>Pattern information</h3><Field label="Pattern title"><input value={p.title} onChange={e=>set('title',e.target.value)} placeholder="e.g. The Marlow Linen Dress"/></Field><Field label="Description" hint={`${p.description.length}/500`}><textarea rows="5" maxLength="500" value={p.description} onChange={e=>set('description',e.target.value)} placeholder="Describe the finished piece, fit and special details…"/></Field><div className="form-grid three"><Field label="Category"><select value={p.category} onChange={e=>set('category',e.target.value)}>{categoryMap[p.type].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Difficulty"><select value={p.difficulty} onChange={e=>set('difficulty',e.target.value)}><option>Beginner</option><option>Confident beginner</option><option>Intermediate</option><option>Advanced</option></select></Field><Field label="Pattern type"><input value={p.type==='sewing'?'Sewing':'Crochet'} disabled/></Field></div><Field label="Available sizes"><ChipInput values={p.sizes} onChange={v=>set('sizes',v)} placeholder="Add size (e.g. M)"/></Field></div><div className="cover-card"><h3>Cover image</h3><CoverArt pattern={p}/><label className="upload-btn"><Icon name="upload"/> Upload cover<input type="file" accept="image/*" onChange={image}/></label><p>JPG or PNG · Up to 3 MB<br/>Portrait images work best.</p></div></div>
      <div className="form-card wide"><h3>Materials & tools</h3><div className="split-fields"><div><h4>Materials</h4><Repeater items={p.materials} onChange={v=>set('materials',v)} newItem={{name:'',quantity:''}} addLabel="Add material" empty="No materials added yet." render={(m,i,change)=><><input value={m.name} onChange={e=>change({name:e.target.value})} placeholder="Material or supply"/><input value={m.quantity} onChange={e=>change({quantity:e.target.value})} placeholder="Quantity"/></>}/></div><div><h4>Tools</h4><Field label="Required tools"><ChipInput values={p.tools} onChange={v=>set('tools',v)} placeholder="Add tool"/></Field></div></div></div>
      <div className="form-card wide"><h3>Measurements</h3><Repeater items={p.measurements} onChange={v=>set('measurements',v)} newItem={{name:'',value:'',unit:'cm'}} addLabel="Add measurement" empty="Add body or finished measurements for a complete PDF." render={(m,i,change)=><><input value={m.name} onChange={e=>change({name:e.target.value})} placeholder="e.g. Finished length"/><input value={m.value} onChange={e=>change({value:e.target.value})} placeholder="Value or range"/><select value={m.unit} onChange={e=>change({unit:e.target.value})}><option>cm</option><option>in</option><option>stitches</option></select></>}/></div>
    </section>}
    {tab==='craft'&&p.type==='sewing'&&<SewingTools p={p} set={set}/>} 
    {tab==='craft'&&p.type==='crochet'&&<CrochetTools p={p} set={set}/>} 
    {tab==='instructions'&&<section className="editor-section"><div className="section-intro"><span className="eyebrow">STEP BY STEP</span><h2>Guide makers with confidence.</h2><p>Break the process into short, useful stages. Drag-and-drop ordering can be added in a production iteration.</p></div><div className="instructions-list"><Repeater items={p.instructions} onChange={v=>set('instructions',v)} newItem={{title:'',body:''}} addLabel="Add instruction step" render={(s,i,change)=><><div className="step-number">{String(i+1).padStart(2,'0')}</div><div className="step-fields"><input value={s.title} onChange={e=>change({title:e.target.value})} placeholder="Step title"/><textarea rows="4" value={s.body} onChange={e=>change({body:e.target.value})} placeholder="Explain this step clearly. Include pressing, finishing or stitch-count notes…"/></div></>}/></div><div className="form-card wide notes-card"><h3>Designer notes</h3><Field label="Additional notes" hint="Shown near the end of the PDF"><textarea rows="5" value={p.notes} onChange={e=>set('notes',e.target.value)} placeholder="Add fit notes, modification ideas, yarn substitutions or care instructions…"/></Field></div></section>}
    {tab==='publish'&&<Publish p={p} set={set} publish={publish} exportPdf={exportPdf} setPreview={setPreview} save={()=>save(true)}/>} 
    </div>{preview&&<><div className="preview-backdrop" onClick={()=>setPreview(false)}/><PatternPreview p={p} onClose={()=>setPreview(false)}/></>}
  </div>
}

function SewingTools({p,set}){
  const tiles=(piece)=>Math.max(1,Math.ceil((Number(piece.width)||1)/19)*Math.ceil((Number(piece.height)||1)/27));
  return <section className="editor-section"><div className="section-intro"><span className="eyebrow">SEWING WORKSPACE</span><h2>Draft the pieces makers need.</h2><p>Define sizing, seam allowances, labels and tile-ready pattern pieces.</p></div><div className="editor-grid balanced"><div className="form-card"><h3>Construction setup</h3><Field label="Garment / item type"><input value={p.garmentType} onChange={e=>set('garmentType',e.target.value)} placeholder="e.g. Midi dress, tote bag"/></Field><div className="form-grid two"><Field label="Default seam allowance"><input value={p.seamAllowance} onChange={e=>set('seamAllowance',e.target.value)} placeholder="1.5 cm"/></Field><Field label="Drafting paper"><select value={p.paperSize} onChange={e=>set('paperSize',e.target.value)}><option>A4</option><option>Letter</option></select></Field></div><label className="toggle-row"><span><b>Include tile assembly guide</b><small>Add print and taping instructions to the PDF</small></span><input type="checkbox" checked={p.tileGuide} onChange={e=>set('tileGuide',e.target.checked)}/><i/></label></div><div className="form-card guide-card"><span className="eyebrow">PRINT SETUP</span><div className="test-square"><span>10 cm</span><b>TEST<br/>SQUARE</b><span>10 cm</span></div><p>Pages export at actual size with a test square and registration marks.</p></div></div>
    <div className="form-card wide"><div className="card-heading"><div><h3>Body size chart</h3><p>Measurements are displayed in centimeters in your PDF.</p></div></div><div className="size-table"><div className="table-row head"><span>Size</span><span>Bust</span><span>Waist</span><span>Hip</span><i/></div><Repeater items={p.sizeChart} onChange={v=>set('sizeChart',v)} newItem={{size:'',bust:'',waist:'',hip:''}} addLabel="Add size" empty="Build a size chart to help makers choose confidently." render={(s,i,change)=><><input value={s.size} onChange={e=>change({size:e.target.value})} placeholder="M"/><input value={s.bust} onChange={e=>change({bust:e.target.value})} placeholder="94"/><input value={s.waist} onChange={e=>change({waist:e.target.value})} placeholder="76"/><input value={s.hip} onChange={e=>change({hip:e.target.value})} placeholder="102"/></>}/></div></div>
    <div className="form-card wide"><div className="card-heading"><div><h3>Printable pattern pieces</h3><p>Dimensions create scaled preview pieces and calculate home-print tiles.</p></div><span className="info-pill">{p.pieces?.reduce((s,x)=>s+tiles(x),0)||0} estimated pages</span></div><div className="pieces"><Repeater items={p.pieces} onChange={v=>set('pieces',v)} newItem={{name:'',width:40,height:50,quantity:1,seamAllowance:p.seamAllowance,label:'',markings:''}} addLabel="Add pattern piece" empty="No pieces yet. Add your first drafted piece." render={(piece,i,change)=><><div className="piece-preview" style={{'--pw':Math.min(110,40+Number(piece.width||0))+'px','--ph':Math.min(125,55+Number(piece.height||0))+'px'}}><span>{i+1}</span><b>{piece.name||'Piece'}</b><small>{tiles(piece)} tiles</small></div><div className="piece-fields"><div className="form-grid three"><Field label="Piece name"><input value={piece.name} onChange={e=>change({name:e.target.value})} placeholder="Front bodice"/></Field><Field label="Width (cm)"><input type="number" value={piece.width} onChange={e=>change({width:e.target.value})}/></Field><Field label="Height (cm)"><input type="number" value={piece.height} onChange={e=>change({height:e.target.value})}/></Field></div><div className="form-grid three"><Field label="Cut label"><input value={piece.label} onChange={e=>change({label:e.target.value})} placeholder="Cut 1 on fold"/></Field><Field label="Seam allowance"><input value={piece.seamAllowance} onChange={e=>change({seamAllowance:e.target.value})}/></Field><Field label="Markings"><input value={piece.markings} onChange={e=>change({markings:e.target.value})} placeholder="Notches, grainline"/></Field></div></div></>}/></div></div>
  </section>
}

function CrochetTools({p,set}){
  return <section className="editor-section"><div className="section-intro"><span className="eyebrow">CROCHET WORKSPACE</span><h2>Make every stitch count.</h2><p>Capture yarn, gauge, abbreviations, rows and a clear symbol chart.</p></div><div className="form-card wide"><h3>Yarn & gauge</h3><div className="form-grid four"><Field label="Yarn type"><input value={p.yarnType} onChange={e=>set('yarnType',e.target.value)} placeholder="Merino blend"/></Field><Field label="Yarn weight"><select value={p.yarnWeight} onChange={e=>set('yarnWeight',e.target.value)}><option value="">Choose weight</option><option>Lace / 0</option><option>Fingering / 1</option><option>Sport / 2</option><option>DK / 3</option><option>Worsted / 4</option><option>Bulky / 5</option><option>Super bulky / 6</option></select></Field><Field label="Hook size"><input value={p.hookSize} onChange={e=>set('hookSize',e.target.value)} placeholder="5 mm / H-8"/></Field><Field label="Gauge"><input value={p.gauge} onChange={e=>set('gauge',e.target.value)} placeholder="16 dc × 9 rows = 10 cm"/></Field></div></div>
    <div className="editor-grid balanced"><div className="form-card"><h3>Stitch abbreviations</h3><Repeater items={p.abbreviations} onChange={v=>set('abbreviations',v)} newItem={{term:'',meaning:''}} addLabel="Add abbreviation" empty="Add the shorthand used in your pattern." render={(a,i,change)=><><input value={a.term} onChange={e=>change({term:e.target.value})} placeholder="dc"/><input value={a.meaning} onChange={e=>change({meaning:e.target.value})} placeholder="double crochet"/></>}/></div><div className="form-card symbol-card"><h3>Symbol chart</h3><p>Enter one diagram row per line. Use spaces between symbols.</p><textarea rows="8" value={(p.diagram||[]).map(r=>r.join(' ')).join('\n')} onChange={e=>set('diagram',e.target.value.split('\n').map(r=>r.trim().split(/\s+/).filter(Boolean)))} placeholder={'○ ○ ○ ○ ○\n† · † · †\n† † † † †'}/><div className="symbol-key"><span>○ chain</span><span>· slip stitch</span><span>† double crochet</span></div></div></div>
    <div className="form-card wide"><div className="card-heading"><div><h3>Rows & rounds</h3><p>Keep instruction and stitch count side-by-side to reduce errors.</p></div><span className="info-pill">{p.rows?.length||0} rows defined</span></div><div className="rows-table"><div className="table-row head"><span>Row / round</span><span>Instruction</span><span>Stitch count</span><i/></div><Repeater items={p.rows} onChange={v=>set('rows',v)} newItem={{number:'',instruction:'',stitchCount:''}} addLabel="Add row or round" empty="Add the foundation row or first round." render={(r,i,change)=><><input value={r.number} onChange={e=>change({number:e.target.value})} placeholder="Row 1"/><textarea rows="2" value={r.instruction} onChange={e=>change({instruction:e.target.value})} placeholder="Ch 3, dc in each stitch across…"/><input value={r.stitchCount} onChange={e=>change({stitchCount:e.target.value})} placeholder="48 sts"/></>}/></div></div>
  </section>
}

function Publish({p,set,publish,exportPdf,setPreview,save}){
  const [collection,setCollection]=useState((p.collections||[]).join(', '));
  return <section className="editor-section"><div className="section-intro"><span className="eyebrow">READY TO SHARE</span><h2>Preview, price and publish.</h2><p>Export for your own store or list directly in the Stitch Market marketplace.</p></div><div className="publish-grid"><div className="publish-preview"><div className="publish-paper"><CoverArt pattern={p}/><span>{p.type} pattern</span><h3>{p.title}</h3><p>{p.description||'Your pattern description will appear here.'}</p><footer><b>{p.category}</b><span>{(p.sizes||[]).join(' · ')}</span></footer></div><button onClick={()=>setPreview(true)}><Icon name="eye"/> Open full preview</button></div><div className="publish-options"><div className="form-card"><div className="publish-status"><Status value={p.status}/><span>{p.status==='published'?'Visible in the marketplace':'Only you can see this pattern'}</span></div><Field label="Pattern price (USD)" hint="Platform fees not included in test mode"><div className="money-input"><span>$</span><input type="number" min="0" step="0.5" value={p.price} onChange={e=>set('price',e.target.value)}/></div></Field><Field label="Collections" hint="Separate multiple collections with commas"><input value={collection} onChange={e=>setCollection(e.target.value)} onBlur={()=>set('collections',collection.split(',').map(x=>x.trim()).filter(Boolean))} placeholder="Spring collection, Best sellers"/></Field><div className="publish-check"><Icon name="check"/><span><b>{p.title&&p.description?'Listing details complete':'Complete title and description'}</b><small>Title, description and category</small></span></div><div className="publish-check"><Icon name={p.instructions?.some(x=>x.body)?'check':'clock'}/><span><b>{p.instructions?.some(x=>x.body)?'Instructions added':'Instructions needed'}</b><small>{p.instructions?.length||0} steps in your pattern</small></span></div><div className="publish-actions"><Btn variant="secondary" icon="check" onClick={save}>Save draft</Btn><Btn icon="store" onClick={publish}>{p.status==='published'?'Update listing':'Publish to market'}</Btn></div></div><div className="form-card export-card"><div><Icon name="download"/><span><h3>Export professional PDF</h3><p>Cover, sections, diagrams and copyright included.</p></span></div><button onClick={()=>exportPdf('a4')}><span><b>A4 pattern PDF</b><small>210 × 297 mm · International</small></span><Icon name="download"/></button><button onClick={()=>exportPdf('letter')}><span><b>US Letter pattern PDF</b><small>8.5 × 11 in · North America</small></span><Icon name="download"/></button></div></div></div></section>
}

function Orders({toast}){
  const [orders,setOrders]=useState(null);useEffect(()=>{request('/orders').then(setOrders).catch(e=>toast(e.message,'error'))},[]);
  return <><PageTitle eyebrow="YOUR PURCHASES" title="Pattern downloads" sub="Every pattern you've purchased, ready whenever inspiration strikes."/><div className="panel orders-panel">{!orders?<Loading/>:orders.length?orders.map(o=><div className="order-row" key={o.id}><CoverArt pattern={o.pattern}/><div className="order-main"><span className={`craft ${o.pattern.type}`}>{o.pattern.type}</span><b>{o.pattern.title}</b><small>Order {o.id.toUpperCase()} · {date(o.createdAt)}</small></div><div className="order-price"><b>{money(o.amount)}</b><span>Paid</span></div><div className="order-download"><Btn variant="secondary" icon="download" onClick={()=>downloadFile(`/orders/${o.id}/download?format=a4`).catch(e=>toast(e.message,'error'))}>A4 PDF</Btn><Btn variant="ghost" onClick={()=>downloadFile(`/orders/${o.id}/download?format=letter`).catch(e=>toast(e.message,'error'))}>Letter</Btn></div></div>):<Empty icon="bag" title="No purchases yet" text="Explore independent patterns in the marketplace."/>}</div></>
}

function Sales({toast}){
  const [data,setData]=useState(null);useEffect(()=>{request('/sales').then(setData).catch(e=>toast(e.message,'error'))},[]);if(!data)return <Loading/>;
  const max=Math.max(1,...data.byPattern.map(x=>x.revenue));
  return <><PageTitle eyebrow="SELLER DASHBOARD" title="Sales & earnings" sub="A clear view of how your pattern catalog is performing." actions={<span className="test-badge"><Icon name="spark"/> Test payment mode</span>}/><section className="stats-grid three-stats"><div className="stat-card dark"><span><Icon name="chart"/></span><div><b>{money(data.summary.revenue)}</b><small>Total revenue</small></div></div><div className="stat-card coral"><span><Icon name="bag"/></span><div><b>{data.summary.orders}</b><small>Paid orders</small></div></div><div className="stat-card sage"><span><Icon name="pattern"/></span><div><b>{money(data.summary.average)}</b><small>Average order</small></div></div></section><div className="sales-grid"><section className="panel"><div className="panel-head"><div><h2>Revenue by pattern</h2><p>Your catalog performance</p></div></div><div className="bar-list">{data.byPattern.map(x=><div key={x.id}><span>{x.title}<small>{x.count} sale{x.count!==1?'s':''}</small></span><i><b style={{width:`${x.revenue/max*100}%`}}/></i><strong>{money(x.revenue)}</strong></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Recent orders</h2><p>Latest customer activity</p></div></div>{data.orders.length?data.orders.slice(0,5).map(o=><div className="sale-row" key={o.id}><Avatar user={o.buyer}/><span><b>{o.buyer.name}</b><small>{o.pattern.title} · {date(o.createdAt)}</small></span><strong>{money(o.amount)}</strong></div>):<Empty icon="chart" title="Sales will appear here" text="Publish a priced pattern to get started."/>}</section></div></>
}

function Profile({user,setUser,toast}){
  const [form,setForm]=useState(user),[busy,setBusy]=useState(false);const save=async e=>{e.preventDefault();setBusy(true);try{const u=await request('/profile',{method:'PUT',body:form});setUser(u);toast('Profile updated.','success')}catch(err){toast(err.message,'error')}finally{setBusy(false)}};
  return <><PageTitle eyebrow="CREATOR PROFILE" title="Your studio identity" sub="This information appears on your marketplace listings."/><div className="profile-grid"><section className="profile-card"><div className="profile-cover"><div className="thread-line"/><Avatar user={form} size="xl"/></div><div><h2>{form.studio||form.name}</h2><p>{form.bio||'Independent pattern creator.'}</p><span><Icon name="pattern"/> Stitch Market creator since {new Date(user.joinedAt).getFullYear()}</span></div></section><form className="form-card" onSubmit={save}><h3>Profile details</h3><div className="form-grid two"><Field label="Your name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Studio name"><input value={form.studio} onChange={e=>setForm({...form,studio:e.target.value})}/></Field></div><Field label="Email"><input value={form.email} disabled/></Field><Field label="Location"><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="City, country"/></Field><Field label="Creator bio" hint={`${form.bio?.length||0}/240`}><textarea rows="5" maxLength="240" value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></Field><Field label="Profile color"><div className="color-row">{['#d77559','#5d7f78','#173f3a','#c69a55','#8d7387'].map(c=><button type="button" className={form.avatarColor===c?'active':''} key={c} style={{background:c}} onClick={()=>setForm({...form,avatarColor:c})}/>)}</div></Field><div className="form-actions"><Btn type="submit" disabled={busy}>{busy?'Saving…':'Save profile'}</Btn></div></form></div></>
}

function NewPattern({initial,onClose,onCreate}){
  const [type,setType]=useState(initial||'sewing'),[title,setTitle]=useState(''),[busy,setBusy]=useState(false);
  const create=async()=>{setBusy(true);try{await onCreate({type,title:title.trim()||`Untitled ${type} pattern`})}finally{setBusy(false)}};
  return <div className="modal-wrap"><div className="modal-backdrop" onClick={onClose}/><div className="modal"><button className="modal-close" onClick={onClose}><Icon name="close"/></button><span className="eyebrow">NEW PATTERN</span><h2>What are you creating?</h2><p>Choose a workspace. You can fill in the details as you go.</p><div className="type-choice"><button className={type==='sewing'?'selected':''} onClick={()=>setType('sewing')}><span><Icon name="scissors" size={27}/></span><b>Sewing pattern</b><small>Garments, bags, homeware & more</small><i><Icon name="check"/></i></button><button className={type==='crochet'?'selected':''} onClick={()=>setType('crochet')}><span><Icon name="yarn" size={27}/></span><b>Crochet pattern</b><small>Wearables, toys, blankets & more</small><i><Icon name="check"/></i></button></div><Field label="Working title" hint="You can change this later"><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==='Enter'&&create()} placeholder={type==='sewing'?'e.g. Summer wrap dress':'e.g. Cloud stitch cardigan'}/></Field><Btn className="full" icon="arrow" disabled={busy} onClick={create}>{busy?'Creating workspace…':'Open pattern editor'}</Btn></div></div>
}

function Toast({toast}){if(!toast)return null;return <div className={`toast ${toast.type||''}`}><span><Icon name={toast.type==='error'?'close':'check'}/></span>{toast.text}</div>}

export default function App(){
  const [user,setUser]=useState(null),[boot,setBoot]=useState(true),[page,setPage]=useState('dashboard'),[editorId,setEditorId]=useState(null),[productId,setProductId]=useState(null),[newModal,setNewModal]=useState(false),[newInitial,setNewInitial]=useState(null),[toast,setToast]=useState(null);
  const notify=useCallback((text,type='info')=>{setToast({text,type});setTimeout(()=>setToast(null),3200)},[]);
  useEffect(()=>{const token=localStorage.getItem('stitch_token');if(!token){setBoot(false);return}request('/auth/me').then(setUser).catch(()=>localStorage.removeItem('stitch_token')).finally(()=>setBoot(false))},[]);
  const navigate=p=>{setPage(p);setEditorId(null);setProductId(null);window.scrollTo(0,0)};
  const edit=id=>{setEditorId(id);setProductId(null);window.scrollTo(0,0)};
  const openProduct=id=>{setProductId(id);window.scrollTo(0,0)};
  const openNew=(type=null)=>{setNewInitial(type);setNewModal(true)};
  const create=async input=>{try{const p=await request('/patterns',{method:'POST',body:input});setNewModal(false);edit(p.id)}catch(e){notify(e.message,'error')}};
  const logout=()=>{localStorage.removeItem('stitch_token');setUser(null);setPage('dashboard')};
  if(boot)return <Loading/>;if(!user)return <><Auth onAuth={setUser}/><Toast toast={toast}/></>;
  let content;
  if(editorId)content=<Editor id={editorId} onBack={()=>navigate('patterns')} toast={notify}/>;
  else if(productId)content=<Product id={productId} user={user} onBack={()=>navigate('marketplace')} onEdit={edit} toast={notify}/>;
  else if(page==='dashboard')content=<Dashboard user={user} navigate={navigate} onNew={openNew} onEdit={edit} toast={notify}/>;
  else if(['patterns','favorites','collections'].includes(page))content=<Library mode={page} onEdit={edit} onNew={openNew} onOpenProduct={openProduct} toast={notify}/>;
  else if(page==='marketplace')content=<Marketplace onOpen={openProduct} toast={notify}/>;
  else if(page==='orders')content=<Orders toast={notify}/>;
  else if(page==='sales')content=<Sales toast={notify}/>;
  else if(page==='profile')content=<Profile user={user} setUser={setUser} toast={notify}/>;
  return <><Shell user={user} page={page} navigate={navigate} onNew={openNew} onLogout={logout}>{content}</Shell>{newModal&&<NewPattern initial={newInitial} onClose={()=>setNewModal(false)} onCreate={create}/>}<Toast toast={toast}/></>;
}
